# Template: secret2
# This file is copied to /opt/course/14/secret2.yaml during setup
# Q14: Student must create this Secret and mount it in secret-handler Pod
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: moon
type: Opaque
data:
  key: YWJjZGVm
  cert: MTIzNDU2
