# ServiceAccounts para el simulador CKAD
# Question 5: neptune-sa-v2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neptune-sa-v2
  namespace: neptune

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-sun-deploy
  namespace: sun
